collections_config:
  api:
    editor: data
    schemas:
      default:
        path: _schemas/api.md
  documentation:
    editor: data
    schemas:
      default:
        path: _schemas/documentation.md

_inputs:
  type:
    type: select
    options:
      values:
        - get
        - put
        - delete
        - post